server:
  port: ${APPLICATION_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${APPLICATION_DB_URL:localhost}:${APPLICATION_DB_PORT:5432}/${APPLICATION_DB_NAME:foodie}
    username: ${APPLICATION_DB_USER:postgres}
    password: ${APPLICATION_DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    openInView: false
    show_sql: true
    generate-ddl: true
  data:
    jpa:
      repositories.enabled: true

